name: "edge"
services:
  core:
    build:
      context: .
      args:
        - DOCKER_UID=${UID:-1000}
        - DOCKER_GID=${GID:-1000}
        - DOCKER_USER=edge
        - DOCKER_GROUP=group
    working_dir: /home/edge/workspace
    volumes:
      - type: bind
        source: .
        target: /home/edge/workspace
        consistency: cached
      - type: volume
        source: node-volume
        target: /home/edge/workspace/node_modules
        volume:
          nocopy: true
    ports:
      - "5170:5170"
      - "5171:5171"
      - "5172:5172"
      - "5173:5173"
      - "8780:8780"
      - "8781:8781"
      - "8782:8782"
    command: sleep infinity
    tty: true
    stdin_open: true
    init: true
    user: edge:group
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
      - ALL_PROXY
      - http_proxy
      - https_proxy
      - no_proxy
      - all_proxy
    restart: unless-stopped
volumes:
  node-volume:
    driver: local
